[build]
  publish = "Public"
  command = "echo 'No build needed'"

[[redirects]]
  from = "/"
  to = "/Login.html"
  status = 200

[[redirects]]
  from = "/student"
  to = "/student/index.html"
  status = 200